apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-backend
  namespace: dev
  labels:
    app: expense-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-backend
  template:
    metadata:
      labels:
        app: expense-backend
    spec:
      containers:
      - name: expense-backend
        image: IMAGE_PLACEHOLDER
        ports:
          - containerPort: 3000
