apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-frontend
  namespace: dev
  labels:
    app: expense-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-frontend
  template:
    metadata:
      labels:
        app: expense-frontend
    spec:
      containers:
      - name: expense-frontend
        image: IMAGE_PLACEHOLDER                                                                                                                  
        ports:
        - containerPort: 3000

