name: Deploy Ingress to EKS

on:
  push:
    branches:
      - dev
    paths:
      - 'k8s/dev/ingress.yml'

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: 3-tier-eks-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name $EKS_CLUSTER_NAME \
          --region $AWS_REGION

    - name: Verify EKS Access
      run: |
        kubectl get nodes

    - name: Deploy Ingress
      run: |
        kubectl apply -f k8s/dev/ingress.yml

    - name: Verify Ingress
      run: |
        kubectl get ingress -n dev
